VAGRANTFILE_API_VERSION = "2"
#Refer to ND1.bmp for network topology refernce

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|


  config.vm.box = "ubuntu/xenial64"
  
  #net1mc1	
         config.vm.define :net1mc1 do |net1mc1|
          net1mc1.vm.provider :virtualbox do |v|
           v.name = "net1mc1"
           v.customize ["modifyvm", :id, "--memory", "2048"]
           v.gui = true
     
         end
         net1mc1.vm.network :private_network, ip: "192.168.10.12"
         net1mc1.vm.hostname = "net1mc1"
         net1mc1.vm.provision :shell, path: "target/scripts/install_vm.sh"
    end
    
    
    #net1mc3	
           config.vm.define :net1mc3 do |net1mc3|
            net1mc3.vm.provider :virtualbox do |v|
             v.name = "net1mc3"
             v.customize ["modifyvm", :id, "--memory", "2048"]
             v.gui = true
       
           end
           net1mc3.vm.network :private_network, ip: "192.168.10.14"
           net1mc3.vm.hostname = "net1mc3"
           net1mc3.vm.provision :shell, path: "target/scripts/install_vm.sh"
    end
    
    #net1mc4	
           config.vm.define :net1mc4 do |net1mc4|
            net1mc4.vm.provider :virtualbox do |v|
             v.name = "net1mc4"
             v.customize ["modifyvm", :id, "--memory", "2048"]
             v.gui = true
       
           end
           net1mc4.vm.network :private_network, ip: "192.168.10.15"
           net1mc4.vm.hostname = "net1mc4"
           net1mc4.vm.provision :shell, path: "target/scripts/install_vm.sh"
    end
   

end